/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package VISTA;

/**
 *
 * @author Jhony Espinoza
 */
public class VistaEliminarP extends javax.swing.JPanel {

    /**
     * Creates new form VistaEliminarP
     */
    public VistaEliminarP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCONTENEDOR1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldNOMBREELI = new javax.swing.JTextField();
        jTextFieldPRECIOELI = new javax.swing.JTextField();
        jComboBoxCATEGORIAELI = new javax.swing.JComboBox<>();
        jSpinnerCANTIDADELI = new javax.swing.JSpinner();
        jTextFieldPROVEEDORELI = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButtonELIMINAR = new javax.swing.JButton();
        jButtonBACK = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldIDELI = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableELI = new javax.swing.JTable();
        jButtonBUSCARELI = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldCODIGOELIMINAR = new javax.swing.JTextField();
        jTextFieldBUSCARELI = new javax.swing.JTextField();

        setMaximumSize(new java.awt.Dimension(830, 390));
        setMinimumSize(new java.awt.Dimension(830, 390));
        setPreferredSize(new java.awt.Dimension(830, 390));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelCONTENEDOR1.setBackground(new java.awt.Color(42, 42, 59));
        jPanelCONTENEDOR1.setPreferredSize(new java.awt.Dimension(830, 390));
        jPanelCONTENEDOR1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ELIMINAR  PRODUCTO");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanelCONTENEDOR1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 14, -1, -1));

        jLabel1.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 242, 242));
        jLabel1.setText("ID:");
        jPanelCONTENEDOR1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, -1, -1));

        jLabel3.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(242, 242, 242));
        jLabel3.setText("Precio:");
        jPanelCONTENEDOR1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(242, 242, 242));
        jLabel4.setText("Cantidad:");
        jPanelCONTENEDOR1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 172, -1, -1));

        jLabel5.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(242, 242, 242));
        jLabel5.setText("Categoria:");
        jPanelCONTENEDOR1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        jLabel6.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(242, 242, 242));
        jLabel6.setText("Proveedor:");
        jPanelCONTENEDOR1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 218, -1, -1));

        jTextFieldNOMBREELI.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldNOMBREELI.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldNOMBREELI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNOMBREELIActionPerformed(evt);
            }
        });
        jPanelCONTENEDOR1.add(jTextFieldNOMBREELI, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 199, -1));

        jTextFieldPRECIOELI.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldPRECIOELI.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jPanelCONTENEDOR1.add(jTextFieldPRECIOELI, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 199, -1));

        jComboBoxCATEGORIAELI.setBackground(new java.awt.Color(204, 204, 204));
        jComboBoxCATEGORIAELI.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanelCONTENEDOR1.add(jComboBoxCATEGORIAELI, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 188, -1));
        jPanelCONTENEDOR1.add(jSpinnerCANTIDADELI, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 178, 92, -1));

        jTextFieldPROVEEDORELI.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldPROVEEDORELI.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jPanelCONTENEDOR1.add(jTextFieldPROVEEDORELI, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 224, 199, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RECURSOS/boxVP.png"))); // NOI18N
        jPanelCONTENEDOR1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 14, -1, -1));

        jButtonELIMINAR.setBackground(new java.awt.Color(42, 42, 59));
        jButtonELIMINAR.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jButtonELIMINAR.setForeground(new java.awt.Color(204, 204, 204));
        jButtonELIMINAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RECURSOS/deleteVE.png"))); // NOI18N
        jButtonELIMINAR.setText("ELIMINAR");
        jButtonELIMINAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonELIMINARActionPerformed(evt);
            }
        });
        jPanelCONTENEDOR1.add(jButtonELIMINAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 294, -1, -1));

        jButtonBACK.setBackground(new java.awt.Color(42, 42, 59));
        jButtonBACK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RECURSOS/arrow-left.png"))); // NOI18N
        jPanelCONTENEDOR1.add(jButtonBACK, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, -1, 53));

        jLabel8.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(242, 242, 242));
        jLabel8.setText("Nombre:");
        jPanelCONTENEDOR1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jTextFieldIDELI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDELIActionPerformed(evt);
            }
        });
        jPanelCONTENEDOR1.add(jTextFieldIDELI, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 110, -1));

        jTableELI.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableELI);

        jPanelCONTENEDOR1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 377, 157));

        jButtonBUSCARELI.setBackground(new java.awt.Color(42, 42, 59));
        jButtonBUSCARELI.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jButtonBUSCARELI.setForeground(new java.awt.Color(204, 204, 204));
        jButtonBUSCARELI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RECURSOS/Buscar.png"))); // NOI18N
        jButtonBUSCARELI.setText("BUSCAR");
        jButtonBUSCARELI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBUSCARELIActionPerformed(evt);
            }
        });
        jPanelCONTENEDOR1.add(jButtonBUSCARELI, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 50, -1, -1));

        jLabel9.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(242, 242, 242));
        jLabel9.setText("Codigo:");
        jPanelCONTENEDOR1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, -1));

        jTextFieldCODIGOELIMINAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCODIGOELIMINARActionPerformed(evt);
            }
        });
        jPanelCONTENEDOR1.add(jTextFieldCODIGOELIMINAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 190, -1));
        jPanelCONTENEDOR1.add(jTextFieldBUSCARELI, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 60, 160, -1));

        add(jPanelCONTENEDOR1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 390));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNOMBREELIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNOMBREELIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNOMBREELIActionPerformed

    private void jTextFieldIDELIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDELIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDELIActionPerformed

    private void jButtonBUSCARELIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBUSCARELIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBUSCARELIActionPerformed

    private void jButtonELIMINARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonELIMINARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonELIMINARActionPerformed

    private void jTextFieldCODIGOELIMINARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCODIGOELIMINARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCODIGOELIMINARActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonBACK;
    public javax.swing.JButton jButtonBUSCARELI;
    public javax.swing.JButton jButtonELIMINAR;
    public javax.swing.JComboBox<String> jComboBoxCATEGORIAELI;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPanelCONTENEDOR1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JSpinner jSpinnerCANTIDADELI;
    public javax.swing.JTable jTableELI;
    public javax.swing.JTextField jTextFieldBUSCARELI;
    public javax.swing.JTextField jTextFieldCODIGOELIMINAR;
    public javax.swing.JTextField jTextFieldIDELI;
    public javax.swing.JTextField jTextFieldNOMBREELI;
    public javax.swing.JTextField jTextFieldPRECIOELI;
    public javax.swing.JTextField jTextFieldPROVEEDORELI;
    // End of variables declaration//GEN-END:variables
}
