/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package VISTA;

/**
 *
 * @author Jhony Espinoza
 */
public class VistaAgregarP extends javax.swing.JPanel {

    /**
     * Creates new form VistaAgregarP
     */
    public VistaAgregarP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCONTENEDOR = new javax.swing.JPanel();
        jPanelCONTENEDOR1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldNOMBREAGREGAR = new javax.swing.JTextField();
        jTextFieldPRECIOAGREGAR = new javax.swing.JTextField();
        jComboBoxCATEGORIA = new javax.swing.JComboBox<>();
        jSpinnerCANTIAD = new javax.swing.JSpinner();
        jTextFieldPROVEEDORAGREGAR = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButtonAGREGAR = new javax.swing.JButton();
        jButtonBACK = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(830, 390));
        setMinimumSize(new java.awt.Dimension(830, 390));
        setPreferredSize(new java.awt.Dimension(830, 390));

        jPanelCONTENEDOR.setBackground(new java.awt.Color(42, 42, 59));

        jPanelCONTENEDOR1.setBackground(new java.awt.Color(42, 42, 59));
        jPanelCONTENEDOR1.setMaximumSize(new java.awt.Dimension(830, 390));
        jPanelCONTENEDOR1.setMinimumSize(new java.awt.Dimension(830, 390));
        jPanelCONTENEDOR1.setPreferredSize(new java.awt.Dimension(830, 390));

        jLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("AGREGAR PRODUCTO");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 0)));

        jLabel1.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 242, 242));
        jLabel1.setText("Nombre:");

        jLabel3.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(242, 242, 242));
        jLabel3.setText("Precio:");

        jLabel4.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(242, 242, 242));
        jLabel4.setText("Cantidad:");

        jLabel5.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(242, 242, 242));
        jLabel5.setText("Categoria:");

        jLabel6.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(242, 242, 242));
        jLabel6.setText("Proveedor:");

        jTextFieldNOMBREAGREGAR.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldNOMBREAGREGAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNOMBREAGREGARActionPerformed(evt);
            }
        });

        jTextFieldPRECIOAGREGAR.setBackground(new java.awt.Color(204, 204, 204));

        jComboBoxCATEGORIA.setBackground(new java.awt.Color(204, 204, 204));
        jComboBoxCATEGORIA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextFieldPROVEEDORAGREGAR.setBackground(new java.awt.Color(204, 204, 204));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RECURSOS/boxVP.png"))); // NOI18N

        jButtonAGREGAR.setBackground(new java.awt.Color(42, 42, 59));
        jButtonAGREGAR.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jButtonAGREGAR.setForeground(new java.awt.Color(0, 255, 0));
        jButtonAGREGAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RECURSOS/add-button.png"))); // NOI18N
        jButtonAGREGAR.setText("AGREGAR");

        jButtonBACK.setBackground(new java.awt.Color(42, 42, 59));
        jButtonBACK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RECURSOS/arrow-left.png"))); // NOI18N

        javax.swing.GroupLayout jPanelCONTENEDOR1Layout = new javax.swing.GroupLayout(jPanelCONTENEDOR1);
        jPanelCONTENEDOR1.setLayout(jPanelCONTENEDOR1Layout);
        jPanelCONTENEDOR1Layout.setHorizontalGroup(
            jPanelCONTENEDOR1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCONTENEDOR1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonBACK)
                .addContainerGap())
            .addGroup(jPanelCONTENEDOR1Layout.createSequentialGroup()
                .addGroup(jPanelCONTENEDOR1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelCONTENEDOR1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldNOMBREAGREGAR, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCONTENEDOR1Layout.createSequentialGroup()
                        .addContainerGap(23, Short.MAX_VALUE)
                        .addGroup(jPanelCONTENEDOR1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelCONTENEDOR1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldPRECIOAGREGAR, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelCONTENEDOR1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldPROVEEDORAGREGAR, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addGroup(jPanelCONTENEDOR1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAGREGAR)
                    .addGroup(jPanelCONTENEDOR1Layout.createSequentialGroup()
                        .addGroup(jPanelCONTENEDOR1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelCONTENEDOR1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSpinnerCANTIAD, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxCATEGORIA, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanelCONTENEDOR1Layout.setVerticalGroup(
            jPanelCONTENEDOR1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCONTENEDOR1Layout.createSequentialGroup()
                .addGroup(jPanelCONTENEDOR1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCONTENEDOR1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanelCONTENEDOR1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel2)))
                    .addGroup(jPanelCONTENEDOR1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonBACK, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(jPanelCONTENEDOR1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldNOMBREAGREGAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jSpinnerCANTIAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanelCONTENEDOR1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBoxCATEGORIA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldPRECIOAGREGAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanelCONTENEDOR1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldPROVEEDORAGREGAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonAGREGAR)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelCONTENEDORLayout = new javax.swing.GroupLayout(jPanelCONTENEDOR);
        jPanelCONTENEDOR.setLayout(jPanelCONTENEDORLayout);
        jPanelCONTENEDORLayout.setHorizontalGroup(
            jPanelCONTENEDORLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCONTENEDORLayout.createSequentialGroup()
                .addComponent(jPanelCONTENEDOR1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 456, Short.MAX_VALUE))
        );
        jPanelCONTENEDORLayout.setVerticalGroup(
            jPanelCONTENEDORLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCONTENEDORLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCONTENEDOR1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 830, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelCONTENEDOR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 458, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelCONTENEDOR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNOMBREAGREGARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNOMBREAGREGARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNOMBREAGREGARActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonAGREGAR;
    public javax.swing.JButton jButtonBACK;
    public javax.swing.JComboBox<String> jComboBoxCATEGORIA;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanelCONTENEDOR;
    public javax.swing.JPanel jPanelCONTENEDOR1;
    public javax.swing.JSpinner jSpinnerCANTIAD;
    public javax.swing.JTextField jTextFieldNOMBREAGREGAR;
    public javax.swing.JTextField jTextFieldPRECIOAGREGAR;
    public javax.swing.JTextField jTextFieldPROVEEDORAGREGAR;
    // End of variables declaration//GEN-END:variables
}
