/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package VISTA;

/**
 *
 * @author Jhony Espinoza
 */
public class VistaEditarP extends javax.swing.JPanel {

    /**
     * Creates new form VistaEditarP
     */
    public VistaEditarP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCONTENEDOR1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldNOMBREEDIT = new javax.swing.JTextField();
        jTextFieldPRECIOEDIT = new javax.swing.JTextField();
        jComboBoxCATEGORIAEDIT = new javax.swing.JComboBox<>();
        jSpinnerCANTIDADEDIT = new javax.swing.JSpinner();
        jTextFieldPROVEEDOREDIT = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButtonEDIT = new javax.swing.JButton();
        jButtonBACK = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldIDEDIT = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEDIT = new javax.swing.JTable();
        jButtonBUSCAREDIT = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(830, 390));
        setMinimumSize(new java.awt.Dimension(830, 390));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelCONTENEDOR1.setBackground(new java.awt.Color(42, 42, 59));
        jPanelCONTENEDOR1.setMaximumSize(new java.awt.Dimension(830, 390));
        jPanelCONTENEDOR1.setMinimumSize(new java.awt.Dimension(830, 390));
        jPanelCONTENEDOR1.setPreferredSize(new java.awt.Dimension(830, 390));
        jPanelCONTENEDOR1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("EDITAR  PRODUCTO");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51)));
        jPanelCONTENEDOR1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 14, 247, -1));

        jLabel1.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 242, 242));
        jLabel1.setText("ID:");
        jPanelCONTENEDOR1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 56, -1, -1));

        jLabel3.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(242, 242, 242));
        jLabel3.setText("Precio:");
        jPanelCONTENEDOR1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 132, -1, -1));

        jLabel4.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(242, 242, 242));
        jLabel4.setText("Cantidad:");
        jPanelCONTENEDOR1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 178, -1, -1));

        jLabel5.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(242, 242, 242));
        jLabel5.setText("Categoria:");
        jPanelCONTENEDOR1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        jLabel6.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(242, 242, 242));
        jLabel6.setText("Proveedor:");
        jPanelCONTENEDOR1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 224, -1, -1));

        jTextFieldNOMBREEDIT.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldNOMBREEDIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNOMBREEDITActionPerformed(evt);
            }
        });
        jPanelCONTENEDOR1.add(jTextFieldNOMBREEDIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 92, 199, -1));

        jTextFieldPRECIOEDIT.setBackground(new java.awt.Color(204, 204, 204));
        jPanelCONTENEDOR1.add(jTextFieldPRECIOEDIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 138, 199, -1));

        jComboBoxCATEGORIAEDIT.setBackground(new java.awt.Color(204, 204, 204));
        jComboBoxCATEGORIAEDIT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanelCONTENEDOR1.add(jComboBoxCATEGORIAEDIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 276, 188, -1));
        jPanelCONTENEDOR1.add(jSpinnerCANTIDADEDIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 184, 92, -1));

        jTextFieldPROVEEDOREDIT.setBackground(new java.awt.Color(204, 204, 204));
        jPanelCONTENEDOR1.add(jTextFieldPROVEEDOREDIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 230, 199, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RECURSOS/boxVP.png"))); // NOI18N
        jPanelCONTENEDOR1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 14, -1, -1));

        jButtonEDIT.setBackground(new java.awt.Color(42, 42, 59));
        jButtonEDIT.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jButtonEDIT.setForeground(new java.awt.Color(255, 153, 0));
        jButtonEDIT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RECURSOS/editVE.png"))); // NOI18N
        jButtonEDIT.setText("EDITAR");
        jPanelCONTENEDOR1.add(jButtonEDIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 307, -1, -1));

        jButtonBACK.setBackground(new java.awt.Color(42, 42, 59));
        jButtonBACK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RECURSOS/arrow-left.png"))); // NOI18N
        jPanelCONTENEDOR1.add(jButtonBACK, new org.netbeans.lib.awtextra.AbsoluteConstraints(754, 6, -1, 53));

        jLabel8.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(242, 242, 242));
        jLabel8.setText("Nombre:");
        jPanelCONTENEDOR1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 86, -1, -1));

        jTextFieldIDEDIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDEDITActionPerformed(evt);
            }
        });
        jPanelCONTENEDOR1.add(jTextFieldIDEDIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(451, 64, -1, -1));

        jTableEDIT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableEDIT);

        jPanelCONTENEDOR1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 377, 157));

        jButtonBUSCAREDIT.setBackground(new java.awt.Color(42, 42, 59));
        jButtonBUSCAREDIT.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jButtonBUSCAREDIT.setForeground(new java.awt.Color(51, 153, 255));
        jButtonBUSCAREDIT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RECURSOS/Buscar.png"))); // NOI18N
        jButtonBUSCAREDIT.setText("BUSCAR");
        jButtonBUSCAREDIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBUSCAREDITActionPerformed(evt);
            }
        });
        jPanelCONTENEDOR1.add(jButtonBUSCAREDIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(527, 56, -1, -1));

        add(jPanelCONTENEDOR1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 390));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNOMBREEDITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNOMBREEDITActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNOMBREEDITActionPerformed

    private void jTextFieldIDEDITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDEDITActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDEDITActionPerformed

    private void jButtonBUSCAREDITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBUSCAREDITActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBUSCAREDITActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonBACK;
    public javax.swing.JButton jButtonBUSCAREDIT;
    public javax.swing.JButton jButtonEDIT;
    public javax.swing.JComboBox<String> jComboBoxCATEGORIAEDIT;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JPanel jPanelCONTENEDOR1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JSpinner jSpinnerCANTIDADEDIT;
    public javax.swing.JTable jTableEDIT;
    public javax.swing.JTextField jTextFieldIDEDIT;
    public javax.swing.JTextField jTextFieldNOMBREEDIT;
    public javax.swing.JTextField jTextFieldPRECIOEDIT;
    public javax.swing.JTextField jTextFieldPROVEEDOREDIT;
    // End of variables declaration//GEN-END:variables
}
