/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VISTA;

import Controlador.ControladorProductos;
import javax.swing.JFrame;

/**
 *
 * @author Jhony Espinoza
 */
public class VistaPrincipal extends javax.swing.JFrame {
    
  private VistaAgregarP vistaAgregar;
    private VistaEditarP vistaEditar;
    private VistaEliminarP vistaEliminar;
    private VistaListaP vistaLista;
    
    // Controlador
    private ControladorProductos controlador;
    
    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
        inicializarSistema();
    }
    private void inicializarSistema() {
        try {
            // Crear instancias de las vistas
            vistaAgregar = new VistaAgregarP();
            vistaEditar = new VistaEditarP();
            vistaEliminar = new VistaEliminarP();
            vistaLista = new VistaListaP();
            
            // Crear controlador
            controlador = new ControladorProductos();
            
            // Configurar el controlador con las vistas
            controlador.configurarVistas(this, vistaAgregar, vistaEditar, vistaEliminar, vistaLista);
            
            
            // Inicialmente ocultar el panel contenedor
            jPanelCONTENEDOR.setVisible(true);
            
            System.out.println("Sistema MVC inicializado correctamente");
            
        } catch (Exception e) {
            System.err.println("Error al inicializar el sistema: " + e.getMessage());
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanelCONTENEDOR = new javax.swing.JPanel();
        jButtonVISTAAGREGARP = new javax.swing.JButton();
        jButtonVISTADITARP = new javax.swing.JButton();
        jButtonVISTAELIMINARP = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonVISTALISTAP = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanelNAVEGACION = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(830, 470));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelCONTENEDOR.setBackground(new java.awt.Color(42, 42, 59));

        jButtonVISTAAGREGARP.setBackground(new java.awt.Color(42, 42, 59));
        jButtonVISTAAGREGARP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RECURSOS/AgregarVP.png"))); // NOI18N
        jButtonVISTAAGREGARP.setMaximumSize(new java.awt.Dimension(140, 130));
        jButtonVISTAAGREGARP.setMinimumSize(new java.awt.Dimension(140, 130));
        jButtonVISTAAGREGARP.setPreferredSize(new java.awt.Dimension(140, 130));
        jButtonVISTAAGREGARP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVISTAAGREGARPActionPerformed(evt);
            }
        });

        jButtonVISTADITARP.setBackground(new java.awt.Color(42, 42, 59));
        jButtonVISTADITARP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RECURSOS/editVP.png"))); // NOI18N
        jButtonVISTADITARP.setMaximumSize(new java.awt.Dimension(140, 130));
        jButtonVISTADITARP.setMinimumSize(new java.awt.Dimension(140, 130));
        jButtonVISTADITARP.setPreferredSize(new java.awt.Dimension(140, 130));

        jButtonVISTAELIMINARP.setBackground(new java.awt.Color(42, 42, 59));
        jButtonVISTAELIMINARP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RECURSOS/DeleteVP.png"))); // NOI18N
        jButtonVISTAELIMINARP.setMaximumSize(new java.awt.Dimension(140, 130));
        jButtonVISTAELIMINARP.setMinimumSize(new java.awt.Dimension(140, 130));
        jButtonVISTAELIMINARP.setPreferredSize(new java.awt.Dimension(140, 130));
        jButtonVISTAELIMINARP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVISTAELIMINARPActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 255, 51));
        jLabel2.setText("NUEVO");

        jLabel3.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 51));
        jLabel3.setText("EDITAR");

        jLabel4.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("ELIMINAR");

        jButtonVISTALISTAP.setBackground(new java.awt.Color(42, 42, 59));
        jButtonVISTALISTAP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RECURSOS/ListVP.png"))); // NOI18N
        jButtonVISTALISTAP.setMaximumSize(new java.awt.Dimension(140, 130));
        jButtonVISTALISTAP.setMinimumSize(new java.awt.Dimension(140, 130));
        jButtonVISTALISTAP.setPreferredSize(new java.awt.Dimension(140, 130));

        jLabel5.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 204));
        jLabel5.setText("PRODUCTOS");

        javax.swing.GroupLayout jPanelCONTENEDORLayout = new javax.swing.GroupLayout(jPanelCONTENEDOR);
        jPanelCONTENEDOR.setLayout(jPanelCONTENEDORLayout);
        jPanelCONTENEDORLayout.setHorizontalGroup(
            jPanelCONTENEDORLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCONTENEDORLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanelCONTENEDORLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonVISTAAGREGARP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCONTENEDORLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(32, 32, 32)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(jPanelCONTENEDORLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonVISTADITARP, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCONTENEDORLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(27, 27, 27)))
                .addGap(60, 60, 60)
                .addGroup(jPanelCONTENEDORLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCONTENEDORLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel4))
                    .addComponent(jButtonVISTAELIMINARP, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(jPanelCONTENEDORLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonVISTALISTAP, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(45, 45, 45))
        );
        jPanelCONTENEDORLayout.setVerticalGroup(
            jPanelCONTENEDORLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCONTENEDORLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(jPanelCONTENEDORLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanelCONTENEDORLayout.createSequentialGroup()
                        .addComponent(jButtonVISTAELIMINARP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCONTENEDORLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanelCONTENEDORLayout.createSequentialGroup()
                            .addComponent(jButtonVISTALISTAP, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelCONTENEDORLayout.createSequentialGroup()
                            .addGroup(jPanelCONTENEDORLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButtonVISTADITARP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonVISTAAGREGARP, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanelCONTENEDORLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)))))
                .addContainerGap(124, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelCONTENEDOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 830, 390));

        jPanelNAVEGACION.setBackground(new java.awt.Color(30, 30, 47));
        jPanelNAVEGACION.setPreferredSize(new java.awt.Dimension(830, 50));

        jLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("GESTION  DE  PRODUCTOS");

        jSeparator1.setBackground(new java.awt.Color(255, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 204, 0));

        jSeparator2.setForeground(new java.awt.Color(255, 0, 0));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RECURSOS/boxVP.png"))); // NOI18N

        javax.swing.GroupLayout jPanelNAVEGACIONLayout = new javax.swing.GroupLayout(jPanelNAVEGACION);
        jPanelNAVEGACION.setLayout(jPanelNAVEGACIONLayout);
        jPanelNAVEGACIONLayout.setHorizontalGroup(
            jPanelNAVEGACIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNAVEGACIONLayout.createSequentialGroup()
                .addContainerGap(239, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(207, 207, 207))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNAVEGACIONLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelNAVEGACIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator1))
                .addContainerGap())
        );
        jPanelNAVEGACIONLayout.setVerticalGroup(
            jPanelNAVEGACIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNAVEGACIONLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(jPanelNAVEGACIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6))
                .addGap(12, 12, 12)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanelNAVEGACION, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVISTAAGREGARPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVISTAAGREGARPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVISTAAGREGARPActionPerformed

    private void jButtonVISTAELIMINARPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVISTAELIMINARPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVISTAELIMINARPActionPerformed

   
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonVISTAAGREGARP;
    public javax.swing.JButton jButtonVISTADITARP;
    public javax.swing.JButton jButtonVISTAELIMINARP;
    public javax.swing.JButton jButtonVISTALISTAP;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JPanel jPanelCONTENEDOR;
    private javax.swing.JPanel jPanelNAVEGACION;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
